apiVersion: v1
Kind: Pod
metadata:
  labels: 
    app: phpinfo
  name: phinfo-po
spec:
  containers:
    -
      args:
        - -f
        - /src/index.php
        - S
        - 0.0.0.0:8080
      command:
        - php
      env:
        - 
          name: JAVA_HOME
          value: /var/lib/java
      image: php:apache
      name: phpinfo-container
      ports: 
        - 
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readonly: true
          subPath: index.php
      workingDir: /src/   
  volumes:
    -
      configMap:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
---      
apiVersion: v1
Kind: ConfigMap
data:
  JAVA_HOME: /var/lib/java
  index.php: <?php phpinfo():?>
immutable: true
metadata:
  name: phpinfo-cm
---
apiVersion: v1
Kind: Service
metadata:
  name:
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: phpinfo
  type: ClusterIP

    
  
